# Generated by Django 3.2.12 on 2022-04-08 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momento_comida', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MomentoComida',
        ),
    ]
