# Generated by Django 3.2.12 on 2022-04-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('momento_comida', '0002_delete_momentocomida'),
    ]

    operations = [
        migrations.CreateModel(
            name='MomentoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_momento', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
