# Generated by Django 3.2.12 on 2022-04-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momento_comida', '0003_momentocomida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momentocomida',
            old_name='nombre',
            new_name='nombre_momento',
        ),
    ]
