# Generated by Django 3.2.12 on 2022-04-18 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comida',
            old_name='nombre',
            new_name='nombre_comida',
        ),
    ]
