# Generated by Django 3.2.12 on 2022-04-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComidaXPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('id_comida', models.IntegerField()),
                ('id_momento', models.IntegerField()),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='PesoXPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.IntegerField()),
                ('fecha_registro', models.DateField()),
            ],
        ),
    ]
