# Generated by Django 3.2.12 on 2022-04-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0001_initial'),
        ('momento_comida', '0003_momentocomida'),
        ('transaccional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comidaxpaciente',
            name='id_comida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comida.comida'),
        ),
        migrations.AlterField(
            model_name='comidaxpaciente',
            name='id_momento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='momento_comida.momentocomida'),
        ),
    ]
